//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteBuilder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sites_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sites_it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiteBuilder.Resources.Sites.it", typeof(Sites_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adkopkokpoksdoakdoskdaod site.
        /// </summary>
        internal static string Add_site {
            get {
                return ResourceManager.GetString("Add site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really sure?.
        /// </summary>
        internal static string Are_you_really_sure_ {
            get {
                return ResourceManager.GetString("Are you really sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action &lt;strong&gt;cannot&lt;/strong&gt; be undone. This will permanently delete the site {{ title }} and all of its &lt;strong&gt;pages&lt;/strong&gt;, &lt;strong&gt;archives&lt;/strong&gt; and &lt;strong&gt;posts&lt;/strong&gt;..
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit site.
        /// </summary>
        internal static string Edit_site {
            get {
                return ResourceManager.GetString("Edit site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostnames.
        /// </summary>
        internal static string Hostnames {
            get {
                return ResourceManager.GetString("Hostnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this should be the default site of the installation..
        /// </summary>
        internal static string If_this_should_be_the_default_site_of_the_installation_ {
            get {
                return ResourceManager.GetString("If this should be the default site of the installation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the name of the site to confirm..
        /// </summary>
        internal static string Please_type_in_the_name_of_the_site_to_confirm_ {
            get {
                return ResourceManager.GetString("Please type in the name of the site to confirm.", resourceCulture);
            }
        }
    }
}
